#!/usr/bin/env bash
# init_env.sh — 每次啟動前執行，自動產生全新隨機密碼並寫入 .env
# 用法：bash init_env.sh
# 不需要手動編輯 .env；每次重新部署前跑一次即可。

set -euo pipefail

ENV_FILE="$(dirname "$0")/.env"

# ── 亂數產生器 ───────────────────────────────────────────────────────────────
rand_hex()  { openssl rand -hex "${1:-16}"; }
rand_pass() {
  local len="${1:-24}"
  LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$len" || true
}
fernet_key() {
  python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
    || openssl rand -base64 32
}

# ── 產生本次密碼 ─────────────────────────────────────────────────────────────
MINIO_ROOT_USER="minio_$(rand_hex 4)"
MINIO_ROOT_PASSWORD="$(rand_pass 24)"

POLARIS_CLIENT_ID="polaris_$(rand_hex 4)"
POLARIS_CLIENT_SECRET="$(rand_pass 32)"

MYSQL_ROOT_PASSWORD="$(rand_pass 24)"
MYSQL_PASSWORD="$(rand_pass 24)"

POSTGRES_PASSWORD="$(rand_pass 24)"

AIRFLOW_ADMIN_PASSWORD="$(rand_pass 20)"
FERNET_KEY="$(fernet_key)"

METABASE_ADMIN_PASSWORD="$(rand_pass 20)"

# ── 寫入 .env ────────────────────────────────────────────────────────────────
cat > "$ENV_FILE" << EOF
# Auto-generated by init_env.sh — $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# DO NOT commit this file. Run init_env.sh again to regenerate all credentials.

# ── MinIO ──────────────────────────────────
MINIO_ROOT_USER=${MINIO_ROOT_USER}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001
MINIO_BUCKET=lakehouse

# ── Apache Polaris ──────────────────────────
POLARIS_PORT=8181
POLARIS_MGMT_PORT=8182
POLARIS_REALM=POLARIS
POLARIS_CLIENT_ID=${POLARIS_CLIENT_ID}
POLARIS_CLIENT_SECRET=${POLARIS_CLIENT_SECRET}
POLARIS_CATALOG=lakehouse

# ── Trino ───────────────────────────────────
TRINO_PORT=8080

# ── MySQL ───────────────────────────────────
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=lakehouse_cache
MYSQL_USER=lakehouse
MYSQL_PASSWORD=${MYSQL_PASSWORD}
MYSQL_PORT=3306

# ── PostgreSQL (Airflow backend) ────────────
POSTGRES_USER=airflow
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=airflow
POSTGRES_PORT=5432

# ── Airflow ─────────────────────────────────
AIRFLOW_PORT=8888
AIRFLOW_ADMIN_USER=admin
AIRFLOW_ADMIN_PASSWORD=${AIRFLOW_ADMIN_PASSWORD}
AIRFLOW__CORE__FERNET_KEY=${FERNET_KEY}
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres:5432/airflow
AIRFLOW__CORE__EXECUTOR=LocalExecutor
AIRFLOW__CORE__LOAD_EXAMPLES=False

# ── Metabase ─────────────────────────────────
METABASE_PORT=3000
METABASE_URL=http://localhost:3000
METABASE_ADMIN_EMAIL=admin@local.com
METABASE_ADMIN_PASSWORD=${METABASE_ADMIN_PASSWORD}
EOF

chmod 600 "$ENV_FILE"

# ── 輸出摘要（供複製到瀏覽器登入用）────────────────────────────────────────
echo ""
echo "✅  .env 已產生（$(date -u '+%Y-%m-%d %H:%M UTC')）"
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  服務登入資訊（本次啟動有效）                         ║"
echo "╠══════════════════════════════════════════════════════╣"
printf "║  MinIO Console  http://localhost:9001\n"
printf "║    user: %-44s║\n" "${MINIO_ROOT_USER}"
printf "║    pass: %-44s║\n" "${MINIO_ROOT_PASSWORD}"
echo "╠══════════════════════════════════════════════════════╣"
printf "║  Airflow        http://localhost:8888\n"
printf "║    user: %-44s║\n" "admin"
printf "║    pass: %-44s║\n" "${AIRFLOW_ADMIN_PASSWORD}"
echo "╠══════════════════════════════════════════════════════╣"
printf "║  Metabase       http://localhost:3000\n"
printf "║    user: %-44s║\n" "admin@local.com"
printf "║    pass: %-44s║\n" "${METABASE_ADMIN_PASSWORD}"
echo "╠══════════════════════════════════════════════════════╣"
printf "║  Trino UI       http://localhost:8080  (no login)\n"
printf "║  MinIO S3 API   http://localhost:9000\n"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "▶  下一步：docker compose up -d"
echo "   或      ./k8s/deploy.sh"
echo ""
