#!/usr/bin/env pwsh
# init_env.ps1 — Generate fresh random credentials and write to .env (Windows)
# Usage:  .\init_env.ps1
# Equivalent to init_env.sh on macOS/Linux.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptDir = $PSScriptRoot
$EnvFile   = Join-Path $ScriptDir '.env'

# ── Random generators ──────────────────────────────────────────────────────────
function New-RandomHex([int]$bytes) {
    $buf = [System.Security.Cryptography.RandomNumberGenerator]::GetBytes($bytes)
    return ($buf | ForEach-Object { '{0:x2}' -f $_ }) -join ''
}

function New-RandomPass([int]$len) {
    $chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'.ToCharArray()
    $buf   = [System.Security.Cryptography.RandomNumberGenerator]::GetBytes($len)
    return -join ($buf | ForEach-Object { $chars[$_ % $chars.Length] })
}

function New-FernetKey() {
    # Try python3, then python, then fall back to raw base64
    foreach ($py in @('python3', 'python')) {
        if (Get-Command $py -ErrorAction SilentlyContinue) {
            $key = & $py -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>$null
            if ($LASTEXITCODE -eq 0 -and $key) { return $key.Trim() }
        }
    }
    # Fallback: 32 random bytes as base64
    $buf = [System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32)
    return [System.Convert]::ToBase64String($buf)
}

# ── Generate credentials ───────────────────────────────────────────────────────
$MinioUser     = "minio_$(New-RandomHex 4)"
$MinioPass     = New-RandomPass 24
$PolarisId     = "polaris_$(New-RandomHex 4)"
$PolarisSecret = New-RandomPass 32
$MysqlRoot     = New-RandomPass 24
$MysqlPass     = New-RandomPass 24
$PostgresPass  = New-RandomPass 24
$AirflowPass   = New-RandomPass 20
$FernetKey     = New-FernetKey
$MetabasePass  = New-RandomPass 20

# ── Write .env (LF line endings for cross-platform kubectl compatibility) ──────
$timestamp  = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss UTC')
$envContent = (
    "# Auto-generated by init_env.ps1 — $timestamp",
    "# DO NOT commit this file. Run init_env.ps1 again to regenerate all credentials.",
    "",
    "# -- MinIO ------------------------------------------",
    "MINIO_ROOT_USER=$MinioUser",
    "MINIO_ROOT_PASSWORD=$MinioPass",
    "MINIO_API_PORT=9000",
    "MINIO_CONSOLE_PORT=9001",
    "MINIO_BUCKET=lakehouse",
    "",
    "# -- Apache Polaris ----------------------------------",
    "POLARIS_PORT=8181",
    "POLARIS_MGMT_PORT=8182",
    "POLARIS_REALM=POLARIS",
    "POLARIS_CLIENT_ID=$PolarisId",
    "POLARIS_CLIENT_SECRET=$PolarisSecret",
    "POLARIS_CATALOG=lakehouse",
    "",
    "# -- Trino -------------------------------------------",
    "TRINO_PORT=8080",
    "",
    "# -- MySQL -------------------------------------------",
    "MYSQL_ROOT_PASSWORD=$MysqlRoot",
    "MYSQL_DATABASE=lakehouse_cache",
    "MYSQL_USER=lakehouse",
    "MYSQL_PASSWORD=$MysqlPass",
    "MYSQL_PORT=3306",
    "",
    "# -- PostgreSQL (Airflow backend) --------------------",
    "POSTGRES_USER=airflow",
    "POSTGRES_PASSWORD=$PostgresPass",
    "POSTGRES_DB=airflow",
    "POSTGRES_PORT=5432",
    "",
    "# -- Airflow -----------------------------------------",
    "AIRFLOW_PORT=8888",
    "AIRFLOW_ADMIN_USER=admin",
    "AIRFLOW_ADMIN_PASSWORD=$AirflowPass",
    "AIRFLOW__CORE__FERNET_KEY=$FernetKey",
    "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:${PostgresPass}@postgres:5432/airflow",
    "AIRFLOW__CORE__EXECUTOR=LocalExecutor",
    "AIRFLOW__CORE__LOAD_EXAMPLES=False",
    "",
    "# -- Metabase ----------------------------------------",
    "METABASE_PORT=3000",
    "METABASE_URL=http://localhost:3000",
    "METABASE_ADMIN_EMAIL=admin@local.com",
    "METABASE_ADMIN_PASSWORD=$MetabasePass",
    "",
    "# -- 時區（所有服務共用） -------------------------",
    "# 修改此處即可統一調整所有服務的時區",
    "TZ=Asia/Taipei"
) -join "`n"

[System.IO.File]::WriteAllText($EnvFile, $envContent + "`n")

# ── Print summary ──────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "✅  .env generated ($timestamp)" -ForegroundColor Green
Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════╗"
Write-Host "║  Service credentials (valid for this deployment)     ║"
Write-Host "╠══════════════════════════════════════════════════════╣"
Write-Host "║  MinIO Console  http://localhost:30901"
Write-Host ("║    user: {0,-44}║" -f $MinioUser)
Write-Host ("║    pass: {0,-44}║" -f $MinioPass)
Write-Host "╠══════════════════════════════════════════════════════╣"
Write-Host "║  Airflow        http://localhost:30888"
Write-Host ("║    user: {0,-44}║" -f "admin")
Write-Host ("║    pass: {0,-44}║" -f $AirflowPass)
Write-Host "╠══════════════════════════════════════════════════════╣"
Write-Host "║  Metabase       http://localhost:30300"
Write-Host ("║    user: {0,-44}║" -f "admin@local.com")
Write-Host ("║    pass: {0,-44}║" -f $MetabasePass)
Write-Host "╠══════════════════════════════════════════════════════╣"
Write-Host "║  Trino UI       http://localhost:30080  (no login)"
Write-Host "║  MinIO S3 API   http://localhost:30900"
Write-Host "╚══════════════════════════════════════════════════════╝"
Write-Host ""
Write-Host "▶  Next step: .\k8s\deploy.ps1" -ForegroundColor Cyan
Write-Host ""
