#!/usr/bin/env python3
"""
generate_pivot_models.py
Reads field_registry.yml and namespace_registry.yml and generates dbt SQL models:
  - fact_metric_hour_wide.sql
  - fact_metric_day_wide.sql
  - fact_metric_month_wide.sql

Usage:
  python platform/generate_pivot_models.py \
    --field-registry contracts/metrics/field_registry.yml \
    --namespace-registry contracts/metrics/namespace_registry.yml \
    --output dbt/models/gold/generated \
    [--dry-run]

Design notes:
  - weighted_avg fields (e.g. conversion_rate) require numerator + denominator
    to be stored as separate columns in hour_wide so day_wide and month_wide
    can correctly re-aggregate without information loss.
  - All generated files start with a header comment documenting the source
    registry and timestamp; do not hand-edit generated files.
  - Weighted-avg component columns are suffixed `_num` and `_den` and are
    marked with a comment so BI tools can hide them from end users.
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")


# ── helpers ──────────────────────────────────────────────────────────────────

GENERATED_HEADER = """\
-- ============================================================
-- AUTO-GENERATED by generate_pivot_models.py
-- Source: {field_registry}
-- Generated: {ts}
-- DO NOT EDIT — re-run the generator to update.
-- ============================================================
"""

DBT_CONFIG = {
    "hour_wide": dict(
        materialized="incremental",
        incremental_strategy="platform_merge_strategy()",
        unique_key="['date_sk', 'hour', 'entity_sk']",
        tags="['gold', 'hour', 'pivot']",
    ),
    "day_wide": dict(
        materialized="incremental",
        incremental_strategy="platform_merge_strategy()",
        unique_key="['date_sk', 'entity_sk']",
        tags="['gold', 'day', 'pivot']",
    ),
    "month_wide": dict(
        materialized="incremental",
        incremental_strategy="platform_merge_strategy()",
        unique_key="['month_sk', 'entity_sk']",
        tags="['gold', 'month', 'pivot']",
    ),
}

# watermark strategy per model
WATERMARK = {
    "hour_wide": (
        "updated_at >= (select coalesce(max(updated_at), timestamp '1900-01-01')"
        " from {{ this }})"
    ),
    "day_wide": (
        "date_sk >= date_add('day', -{{ var('day_wide_lookback_days', 7) }}, current_date)"
    ),
    "month_wide": (
        "month_sk >= cast(date_format(date_add('month',"
        " -{{ var('month_wide_lookback_months', 2) }}, current_date), '%Y%m') as bigint)"
    ),
}


def _config_block(model: str) -> str:
    cfg = DBT_CONFIG[model]
    lines = [
        "{{ config(",
        f"    materialized='{cfg['materialized']}',",
        f"    table_type=platform_iceberg_table_type(),",
        f"    incremental_strategy={cfg['incremental_strategy']},",
        f"    unique_key={cfg['unique_key']},",
        f"    tags={cfg['tags']}",
        ") }}",
    ]
    return "\n".join(lines)


def _field_sk(field_code: str) -> str:
    return "{{{{ field_sk('{code}') }}}}".format(code=field_code)


# ── field classification ──────────────────────────────────────────────────────

def expose_fields(fields: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return only fields marked expose_to_bi (default True)."""
    return [f for f in fields if f.get("expose_to_bi", True)]


def is_weighted_avg(field: dict[str, Any]) -> bool:
    agg = field.get("aggregation", {})
    return agg.get("hour_to_day") == "weighted_avg"


def ratio_components(field: dict[str, Any]) -> tuple[str, str]:
    """Return (numerator_field_code, denominator_field_code)."""
    return field["numerator_field"], field["denominator_field"]


# ── SQL generators ────────────────────────────────────────────────────────────

def gen_hour_wide(fields: list[dict[str, Any]], source_ref: str) -> str:
    """
    Pivot fact_metric_hour_long → fact_metric_hour_wide.

    For weighted_avg fields, two extra component columns (_num, _den) are
    generated so day_wide can correctly re-aggregate.
    """
    lines: list[str] = []
    lines.append(_config_block("hour_wide"))
    lines.append("")
    lines.append(f"with src as (")
    lines.append(f"    select * from {{{{ ref('{source_ref}') }}}}")
    lines.append(f"    {{% if is_incremental() %}}")
    lines.append(f"    where {WATERMARK['hour_wide']}")
    lines.append(f"    {{% endif %}}")
    lines.append(")")
    lines.append("")
    lines.append("select")
    lines.append("    date_sk,")
    lines.append("    hour,")
    lines.append("    month_sk,")
    lines.append("    entity_sk,")
    lines.append("    source_system_sk,")

    for field in fields:
        code = field["field_code"]
        vtype = field.get("value_type", "decimal")
        agg_fn = field.get("aggregation", {}).get("day_to_month", "sum")

        if is_weighted_avg(field):
            num_code, den_code = ratio_components(field)
            lines.append(
                f"    -- {code}: ratio = {num_code} / {den_code}"
            )
            lines.append(
                f"    sum(case when field_sk = {_field_sk(num_code)}"
                f" then value_decimal else 0 end)"
                f" as {code}_num,  -- component; hide in BI"
            )
            lines.append(
                f"    sum(case when field_sk = {_field_sk(den_code)}"
                f" then value_decimal else 0 end)"
                f" as {code}_den,  -- component; hide in BI"
            )
            lines.append(
                f"    try_cast("
            )
            lines.append(
                f"      sum(case when field_sk = {_field_sk(num_code)}"
                f" then value_decimal else 0 end)"
            )
            lines.append(
                f"      / nullif(sum(case when field_sk = {_field_sk(den_code)}"
                f" then value_decimal else 0 end), 0)"
            )
            lines.append(f"    as double) as {code},")
        else:
            agg = field.get("aggregation", {}).get("hour_to_day", "sum").upper()
            value_col = "value_double" if vtype == "double" else "value_decimal"
            lines.append(
                f"    {agg}(case when field_sk = {_field_sk(code)}"
                f" then {value_col} else 0 end) as {code},"
            )

    lines.append("    max(updated_at) as updated_at")
    lines.append("from src")
    lines.append("group by 1,2,3,4,5")
    return "\n".join(lines)


def gen_day_wide(fields: list[dict[str, Any]], source_ref: str) -> str:
    """
    Aggregate fact_metric_hour_wide → fact_metric_day_wide.

    weighted_avg fields use the _num/_den component columns for correctness.
    """
    lines: list[str] = []
    lines.append(_config_block("day_wide"))
    lines.append("")
    lines.append(f"with src as (")
    lines.append(f"    select * from {{{{ ref('{source_ref}') }}}}")
    lines.append(f"    {{% if is_incremental() %}}")
    lines.append(f"    where {WATERMARK['day_wide']}")
    lines.append(f"    {{% endif %}}")
    lines.append(")")
    lines.append("")
    lines.append("select")
    lines.append("    date_sk,")
    lines.append("    month_sk,")
    lines.append("    entity_sk,")
    lines.append("    source_system_sk,")

    for field in fields:
        code = field["field_code"]
        vtype = field.get("value_type", "decimal")

        if is_weighted_avg(field):
            lines.append(f"    -- {code}: re-aggregate components for correctness")
            lines.append(
                f"    sum({code}_num) as {code}_num,  -- component; hide in BI"
            )
            lines.append(
                f"    sum({code}_den) as {code}_den,  -- component; hide in BI"
            )
            lines.append(
                f"    try_cast(sum({code}_num) / nullif(sum({code}_den), 0) as double)"
                f" as {code},"
            )
        else:
            agg = field.get("aggregation", {}).get("hour_to_day", "sum").upper()
            lines.append(f"    {agg}({code}) as {code},")

    lines.append("    max(updated_at) as updated_at")
    lines.append("from src")
    lines.append("group by 1,2,3,4")
    return "\n".join(lines)


def gen_month_wide(fields: list[dict[str, Any]], source_ref: str) -> str:
    """
    Aggregate fact_metric_day_wide → fact_metric_month_wide.
    """
    lines: list[str] = []
    lines.append(_config_block("month_wide"))
    lines.append("")
    lines.append(f"with src as (")
    lines.append(f"    select * from {{{{ ref('{source_ref}') }}}}")
    lines.append(f"    {{% if is_incremental() %}}")
    lines.append(f"    where {WATERMARK['month_wide']}")
    lines.append(f"    {{% endif %}}")
    lines.append(")")
    lines.append("")
    lines.append("select")
    lines.append("    month_sk,")
    lines.append("    entity_sk,")
    lines.append("    source_system_sk,")

    for field in fields:
        code = field["field_code"]

        if is_weighted_avg(field):
            lines.append(f"    -- {code}: re-aggregate components for correctness")
            lines.append(
                f"    sum({code}_num) as {code}_num,  -- component; hide in BI"
            )
            lines.append(
                f"    sum({code}_den) as {code}_den,  -- component; hide in BI"
            )
            lines.append(
                f"    try_cast(sum({code}_num) / nullif(sum({code}_den), 0) as double)"
                f" as {code},"
            )
        else:
            agg = field.get("aggregation", {}).get("day_to_month", "sum").upper()
            lines.append(f"    {agg}({code}) as {code},")

    lines.append("    max(updated_at) as updated_at")
    lines.append("from src")
    lines.append("group by 1,2,3")
    return "\n".join(lines)


# ── entry point ───────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate dbt pivot models from field_registry.yml")
    p.add_argument("--field-registry", required=True, help="Path to field_registry.yml")
    p.add_argument("--namespace-registry", required=False, help="Path to namespace_registry.yml")
    p.add_argument("--output", required=True, help="Output directory for generated SQL files")
    p.add_argument("--dry-run", action="store_true", help="Print SQL to stdout; do not write files")
    return p.parse_args()


def load_yaml(path: str) -> dict[str, Any]:
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def write_model(
    path: Path,
    content: str,
    field_registry: str,
    dry_run: bool,
) -> None:
    header = GENERATED_HEADER.format(
        field_registry=field_registry,
        ts=datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    )
    full = header + "\n" + content + "\n"

    if dry_run:
        print(f"\n{'='*60}")
        print(f"-- FILE: {path}")
        print('='*60)
        print(full)
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(full, encoding="utf-8")
        print(f"  written: {path}")


def validate_registry(fields: list[dict[str, Any]]) -> None:
    """Fail fast if registry has structural problems."""
    errors: list[str] = []
    seen_codes: set[str] = set()
    for f in fields:
        code = f.get("field_code")
        if not code:
            errors.append("field missing 'field_code'")
            continue
        if code in seen_codes:
            errors.append(f"duplicate field_code: {code}")
        seen_codes.add(code)

        if is_weighted_avg(f):
            for key in ("numerator_field", "denominator_field"):
                if key not in f:
                    errors.append(
                        f"field '{code}' has hour_to_day=weighted_avg but missing '{key}'"
                    )
            # check that the component fields exist in registry
            for component in (f.get("numerator_field"), f.get("denominator_field")):
                if component and component not in seen_codes:
                    # warn only; component may appear later in registry
                    pass

    if errors:
        for e in errors:
            print(f"  ERROR: {e}", file=sys.stderr)
        sys.exit(1)


def main() -> None:
    args = parse_args()
    print(f"generate_pivot_models: reading {args.field_registry}")

    registry = load_yaml(args.field_registry)
    all_fields: list[dict[str, Any]] = registry.get("fields", [])
    validate_registry(all_fields)

    fields = expose_fields(all_fields)
    print(f"  {len(fields)} fields to expose (of {len(all_fields)} total)")

    out = Path(args.output)
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    models = [
        (
            out / "fact_metric_hour_wide.sql",
            gen_hour_wide(fields, "fact_metric_hour_long"),
        ),
        (
            out / "fact_metric_day_wide.sql",
            gen_day_wide(fields, "fact_metric_hour_wide"),
        ),
        (
            out / "fact_metric_month_wide.sql",
            gen_month_wide(fields, "fact_metric_day_wide"),
        ),
    ]

    for path, content in models:
        write_model(path, content, args.field_registry, args.dry_run)

    if not args.dry_run:
        print(f"  done — {len(models)} files written to {out}")
    else:
        print(f"\n[dry-run] {len(models)} files would be written to {out}")


if __name__ == "__main__":
    main()
